

SET SERVEROUTPUT ON  --ENABLE TO PRINT ON SCREEN

/*
VARIABLES 
CHAR (LENGTH), VARCHAR2(LENGTH), LONG, LONG RAW, NUMBER(PRECISION, ESCALA), BINAY_INTEGER, PLS_INTEGER, BOOLEAN, BINARY_FLOAT, BINARY_DOUBLE, DATE, TIMESTAMP, TIMESTAMP WITH  TIME ZONE .... 
*/

--Definition variables
DECLARE 
    NAME VARCHAR2(100);
    LASTNAME VARCHAR2(100);

--Bloque anónimo 
BEGIN
    NAME:='JHOAN';
    LASTNAME:='SAAVEDRA';
    DBMS_OUTPUT.PUT_LINE(LASTNAME);
    DBMS_OUTPUT.PUT_LINE(100); --PINTAR POR PANTALLA
    DBMS_OUTPUT.PUT_LINE(NAME||' ' ||LASTNAME); -- concatation
    --NULL; --Con esto no da fallo si solo está BEGIN y END
END;