SET SERVEROUTPUT ON;

/*
THE SAME CONTEXT WITH RESPECT THE VARIABLES GLOBALS AND LOCAL
*/
DECLARE 
    X NUMBER:=20; --GLOBAL
    Z NUMBER:=30;
BEGIN
    DBMS_OUTPUT.PUT_LINE('X:='||X);
    DECLARE 
        X NUMBER:=10; --LOCAL
    BEGIN
        DBMS_OUTPUT.PUT_LINE('X:='||X);
        DBMS_OUTPUT.PUT_LINE('Z:='||Z);
    END;
END;