SET SERVEROUTPUT ON;

DECLARE
    BONUS NUMBER;

-- SEARCHED CASE
BEGIN
    BONUS:=100;
    CASE 
        WHEN BONUS>500 THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
        WHEN BONUS<=500 AND BONUS >250 THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
        ELSE DBMS_OUTPUT.PUT_LINE('POOR!!!');    
    END CASE;
END;