CREATE OR REPLACE PACKAGE PACK3
IS 
    FUNCTION CONVERT ( NAME VARCHAR2, CONVERSION_TYPE CHAR) RETURN VARCHAR2;
END;
/
CREATE OR REPLACE PACKAGE BODY PACK3
IS

--THOSE TWO FUNCTION ONLY CAN USE IN THIS PACKAGE.

FUNCTION UP(NAME VARCHAR2)
RETURN VARCHAR2
IS BEGIN
    RETURN UPPER(NAME);
END UP;

FUNCTION DO (NAME VARCHAR2)
RETURN VARCHAR2
IS BEGIN
RETURN LOWER(NAME);
END DO;

FUNCTION CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR) RETURN VARCHAR2
IS 
BEGIN

    IF CONVERSION_TYPE='U' THEN
        RETURN(UP(NAME));
    ELSIF CONVERSION_TYPE='L' THEN
        RETURN(DO(NAME));
    ELSE
        DBMS_OUTPUT.PUT_LINE('EL PARAMETRO DEBE SER U O L');
    END IF;
END CONVERT;
END PACK3;


--Execution
--Execution

SET SERVEROUTPUT ON 

DECLARE
    V1 VARCHAR2(100);
BEGIN 
    V1:=PACK3.CONVERT('AAAAA','L');
    DBMS_OUTPUT.PUT_LINE(V1);
END;
/
--Using function
SELECT
    first_name, PACK3.CONVERT(FIRST_NAME,'U')
FROM
    employees;