CREATE OR REPLACE 
PACKAGE PACK4 AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
    FUNCTION COUNT_EMPLOYEES(ID NUMBER) RETURN NUMBER;
    FUNCTION COUNT_EMPLOYEES(ID VARCHAR2) RETURN NUMBER;
END PACK4;
/
CREATE OR REPLACE
PACKAGE BODY PACK4 AS

  FUNCTION COUNT_EMPLOYEES(ID NUMBER) RETURN NUMBER AS
  X NUMBER;
  BEGIN
    SELECT COUNT(*) INTO X FROM EMPLOYEES WHERE department_id=ID;
    RETURN X;
  END COUNT_EMPLOYEES;

  FUNCTION COUNT_EMPLOYEES(ID VARCHAR2) RETURN NUMBER AS
  X NUMBER;
  BEGIN
    SELECT COUNT(*) INTO X FROM EMPLOYEES E INNER JOIN departments D ON e.department_id=d.department_id WHERE d.department_name=ID;
    RETURN X;
  END COUNT_EMPLOYEES;

END PACK4;

--Execution
/
SET SERVEROUTPUT ON;
BEGIN
    dbms_output.put_line(pack4.count_employees(50));
end;